name: Login, Build , Automatic tag and  Push on Artifact-artifactory using Github Actions

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: Build and Push to the Artifact registry
    runs-on: ubuntu-latest
    env:
       ARTIFACT_REGISTRY:  europe-west1-docker.pkg.dev
       DOCKER_IMAGE: europe-west1-docker.pkg.dev/develop-368517/app-test/image-test
       DOCKER_TAG: 1.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: europe-west1-docker.pkg.dev/develop-368517/app-test1/image-test

      - name: Login to Artifact registry
        uses: docker/login-action@v2
        with:
          registry:  europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
