name: Login, Build and Push on Artifact-artifactory using Github Actions

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
         images: europe-west1-docker.pkg.dev/develop-368517/app-test

      - name: Login to Artifact registry
        uses: docker/login-action@v2
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: project/Dockerfile
          push: true
          tags: value=1.0.0
