name: Login, Build and Push on Artifact-artifactory using Github Actions

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ../../project/
          push: true
          tags: europe-west1-docker.pkg.dev/develop-368517/app-test:1.0.0
